spring.application.name=my-popote-api

# ===============================
# DATABASE - MariaDB Cloud
# ===============================
spring.datasource.url=jdbc:mariadb://serverless-europe-west9.sysp0000.db2.skysql.com:4041/my_popote?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
# Le schéma sera créé et géré par nos scripts SQL
spring.jpa.hibernate.ddl-auto=none

# Affiche les requêtes SQL pendant le développement
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================
server.port=8080